-- CreateEnum
CREATE TYPE "AttachmentScope" AS ENUM ('COURSE', 'LESSON');

-- CreateEnum
CREATE TYPE "GamificationContentType" AS ENUM ('QUIZ', 'FLASHCARDS');

-- CreateEnum
CREATE TYPE "GamificationStatus" AS ENUM ('DRAFT', 'GENERATING', 'READY', 'FAILED');

-- AlterEnum
ALTER TYPE "BlockType" ADD VALUE 'GAMIFICATION';

-- AlterTable
ALTER TABLE "Attachment" ADD COLUMN     "scope" "AttachmentScope" NOT NULL DEFAULT 'LESSON';

-- AlterTable
ALTER TABLE "Quiz" ADD COLUMN     "autoGenerated" BOOLEAN NOT NULL DEFAULT false;

-- CreateTable
CREATE TABLE "GamificationBlock" (
    "id" TEXT NOT NULL,
    "lessonBlockId" TEXT NOT NULL,
    "requestedById" TEXT NOT NULL,
    "contentType" "GamificationContentType" NOT NULL,
    "status" "GamificationStatus" NOT NULL DEFAULT 'DRAFT',
    "sourceAttachmentIds" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "config" JSONB,
    "result" JSONB,
    "openAiRunId" TEXT,
    "quizId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "GamificationBlock_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FlashcardDeck" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "createdByProfileId" TEXT NOT NULL,
    "gamificationBlockId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "isPublished" BOOLEAN NOT NULL DEFAULT false,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FlashcardDeck_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FlashcardCard" (
    "id" TEXT NOT NULL,
    "deckId" TEXT NOT NULL,
    "position" INTEGER NOT NULL DEFAULT 0,
    "front" TEXT NOT NULL,
    "back" TEXT NOT NULL,
    "points" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FlashcardCard_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "GamificationBlock_lessonBlockId_key" ON "GamificationBlock"("lessonBlockId");

-- CreateIndex
CREATE UNIQUE INDEX "GamificationBlock_quizId_key" ON "GamificationBlock"("quizId");

-- CreateIndex
CREATE INDEX "GamificationBlock_requestedById_idx" ON "GamificationBlock"("requestedById");

-- CreateIndex
CREATE UNIQUE INDEX "FlashcardDeck_gamificationBlockId_key" ON "FlashcardDeck"("gamificationBlockId");

-- CreateIndex
CREATE INDEX "FlashcardDeck_companyId_idx" ON "FlashcardDeck"("companyId");

-- CreateIndex
CREATE INDEX "FlashcardDeck_createdByProfileId_idx" ON "FlashcardDeck"("createdByProfileId");

-- CreateIndex
CREATE INDEX "FlashcardCard_deckId_idx" ON "FlashcardCard"("deckId");

-- CreateIndex
CREATE UNIQUE INDEX "FlashcardCard_deckId_position_key" ON "FlashcardCard"("deckId", "position");

-- AddForeignKey
ALTER TABLE "GamificationBlock" ADD CONSTRAINT "GamificationBlock_lessonBlockId_fkey" FOREIGN KEY ("lessonBlockId") REFERENCES "LessonBlock"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GamificationBlock" ADD CONSTRAINT "GamificationBlock_requestedById_fkey" FOREIGN KEY ("requestedById") REFERENCES "UserProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GamificationBlock" ADD CONSTRAINT "GamificationBlock_quizId_fkey" FOREIGN KEY ("quizId") REFERENCES "Quiz"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FlashcardDeck" ADD CONSTRAINT "FlashcardDeck_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FlashcardDeck" ADD CONSTRAINT "FlashcardDeck_createdByProfileId_fkey" FOREIGN KEY ("createdByProfileId") REFERENCES "UserProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FlashcardDeck" ADD CONSTRAINT "FlashcardDeck_gamificationBlockId_fkey" FOREIGN KEY ("gamificationBlockId") REFERENCES "GamificationBlock"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FlashcardCard" ADD CONSTRAINT "FlashcardCard_deckId_fkey" FOREIGN KEY ("deckId") REFERENCES "FlashcardDeck"("id") ON DELETE CASCADE ON UPDATE CASCADE;
